# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'IMC.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(552, 238)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 0, 121, 31))
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 50, 231, 91))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 101, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(10, 60, 91, 21))
        self.label_3.setObjectName("label_3")
        self.lineEditEstatura = QtWidgets.QLineEdit(self.frame)
        self.lineEditEstatura.setGeometry(QtCore.QRect(110, 20, 113, 20))
        self.lineEditEstatura.setObjectName("lineEditEstatura")
        self.lineEditPeso = QtWidgets.QLineEdit(self.frame)
        self.lineEditPeso.setGeometry(QtCore.QRect(110, 60, 113, 20))
        self.lineEditPeso.setObjectName("lineEditPeso")
        self.btBorrar = QtWidgets.QPushButton(self.centralwidget)
        self.btBorrar.setGeometry(QtCore.QRect(150, 140, 75, 23))
        self.btBorrar.setObjectName("btBorrar")
        self.btCalcular = QtWidgets.QPushButton(self.centralwidget)
        self.btCalcular.setGeometry(QtCore.QRect(150, 170, 75, 23))
        self.btCalcular.setObjectName("btCalcular")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(250, 50, 301, 91))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(70, 0, 47, 13))
        self.label_4.setObjectName("label_4")
        self.rbHombre = QtWidgets.QRadioButton(self.frame_2)
        self.rbHombre.setGeometry(QtCore.QRect(30, 20, 82, 17))
        self.rbHombre.setObjectName("rbHombre")
        self.rbMujer = QtWidgets.QRadioButton(self.frame_2)
        self.rbMujer.setGeometry(QtCore.QRect(30, 40, 82, 17))
        self.rbMujer.setObjectName("rbMujer")
        self.rbNA = QtWidgets.QRadioButton(self.frame_2)
        self.rbNA.setGeometry(QtCore.QRect(30, 60, 251, 31))
        self.rbNA.setObjectName("rbNA")
        self.resultado = QtWidgets.QLabel(self.centralwidget)
        self.resultado.setGeometry(QtCore.QRect(330, 160, 121, 31))
        self.resultado.setObjectName("resultado")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 552, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "CALCULA TU IMC"))
        self.label_2.setText(_translate("MainWindow", "Ingresa tu estatura"))
        self.label_3.setText(_translate("MainWindow", "Ingresa tu peso"))
        self.lineEditEstatura.setToolTip(_translate("MainWindow", "<html><head/><body><p>Ejemplo: 1.56</p></body></html>"))
        self.lineEditPeso.setToolTip(_translate("MainWindow", "<html><head/><body><p>Ejemplo: 45</p></body></html>"))
        self.btBorrar.setText(_translate("MainWindow", "Borrar"))
        self.btCalcular.setText(_translate("MainWindow", "Calcular"))
        self.label_4.setText(_translate("MainWindow", "Género"))
        self.rbHombre.setText(_translate("MainWindow", "Hombre"))
        self.rbMujer.setText(_translate("MainWindow", "Mujer"))
        self.rbNA.setText(_translate("MainWindow", "Camión 4x4 16 velocidades, todo terreno, azul"))
        self.resultado.setText(_translate("MainWindow", "Resultado"))
