# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'int.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(760, 585)
        MainWindow.setStyleSheet("background-color: rgb(167, 127, 200);\n"
"background-color: rgb(255, 170, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(70, 0, 581, 51))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(28)
        font.setItalic(False)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("background-color: rgb(0, 255, 0);\n"
"background-color: rgb(255, 170, 255);")
        self.label_18.setObjectName("label_18")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(350, 70, 271, 241))
        self.frame_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"background-color: rgb(246, 255, 215);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_14 = QtWidgets.QLabel(self.frame_2)
        self.label_14.setGeometry(QtCore.QRect(10, 50, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.frame_2)
        self.label_15.setGeometry(QtCore.QRect(10, 90, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.frame_2)
        self.label_16.setGeometry(QtCore.QRect(10, 130, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.nombre_cliente = QtWidgets.QLineEdit(self.frame_2)
        self.nombre_cliente.setGeometry(QtCore.QRect(90, 50, 161, 20))
        self.nombre_cliente.setObjectName("nombre_cliente")
        self.telefono_cliente = QtWidgets.QLineEdit(self.frame_2)
        self.telefono_cliente.setGeometry(QtCore.QRect(90, 90, 171, 20))
        self.telefono_cliente.setObjectName("telefono_cliente")
        self.direccion_cliente = QtWidgets.QLineEdit(self.frame_2)
        self.direccion_cliente.setGeometry(QtCore.QRect(90, 130, 171, 20))
        self.direccion_cliente.setObjectName("direccion_cliente")
        self.label_17 = QtWidgets.QLabel(self.frame_2)
        self.label_17.setGeometry(QtCore.QRect(70, 10, 171, 16))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_19 = QtWidgets.QLabel(self.frame_2)
        self.label_19.setGeometry(QtCore.QRect(10, 170, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.numero_cliente = QtWidgets.QLineEdit(self.frame_2)
        self.numero_cliente.setGeometry(QtCore.QRect(90, 170, 171, 20))
        self.numero_cliente.setObjectName("numero_cliente")
        self.enviar_botton = QtWidgets.QPushButton(self.frame_2)
        self.enviar_botton.setGeometry(QtCore.QRect(190, 210, 75, 23))
        self.enviar_botton.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.enviar_botton.setObjectName("enviar_botton")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(20, 70, 311, 341))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"background-color: rgb(170, 170, 255);")
        self.textBrowser.setObjectName("textBrowser")
        self.rb1 = QtWidgets.QRadioButton(self.centralwidget)
        self.rb1.setGeometry(QtCore.QRect(290, 100, 16, 20))
        self.rb1.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.rb1.setText("")
        self.rb1.setObjectName("rb1")
        self.rb2 = QtWidgets.QRadioButton(self.centralwidget)
        self.rb2.setGeometry(QtCore.QRect(290, 130, 16, 20))
        self.rb2.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.rb2.setText("")
        self.rb2.setObjectName("rb2")
        self.rb3 = QtWidgets.QRadioButton(self.centralwidget)
        self.rb3.setGeometry(QtCore.QRect(290, 150, 16, 20))
        self.rb3.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.rb3.setText("")
        self.rb3.setObjectName("rb3")
        self.rb4 = QtWidgets.QRadioButton(self.centralwidget)
        self.rb4.setGeometry(QtCore.QRect(290, 180, 16, 20))
        self.rb4.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.rb4.setText("")
        self.rb4.setObjectName("rb4")
        self.rb5 = QtWidgets.QRadioButton(self.centralwidget)
        self.rb5.setGeometry(QtCore.QRect(290, 210, 16, 20))
        self.rb5.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.rb5.setText("")
        self.rb5.setObjectName("rb5")
        self.rb6 = QtWidgets.QRadioButton(self.centralwidget)
        self.rb6.setGeometry(QtCore.QRect(290, 240, 16, 20))
        self.rb6.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.rb6.setText("")
        self.rb6.setObjectName("rb6")
        self.rb7 = QtWidgets.QRadioButton(self.centralwidget)
        self.rb7.setGeometry(QtCore.QRect(290, 260, 16, 20))
        self.rb7.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.rb7.setText("")
        self.rb7.setObjectName("rb7")
        self.rb8 = QtWidgets.QRadioButton(self.centralwidget)
        self.rb8.setGeometry(QtCore.QRect(290, 290, 16, 20))
        self.rb8.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.rb8.setText("")
        self.rb8.setObjectName("rb8")
        self.rb9 = QtWidgets.QRadioButton(self.centralwidget)
        self.rb9.setGeometry(QtCore.QRect(290, 320, 16, 20))
        self.rb9.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.rb9.setText("")
        self.rb9.setObjectName("rb9")
        self.rb10 = QtWidgets.QRadioButton(self.centralwidget)
        self.rb10.setGeometry(QtCore.QRect(290, 350, 16, 20))
        self.rb10.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.rb10.setText("")
        self.rb10.setObjectName("rb10")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(130, 80, 61, 16))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.label_20.setObjectName("label_20")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(350, 320, 271, 141))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(30, 30, 61, 16))
        self.label.setObjectName("label")
        self.repartidor_datos = QtWidgets.QLineEdit(self.frame)
        self.repartidor_datos.setGeometry(QtCore.QRect(90, 30, 171, 20))
        self.repartidor_datos.setObjectName("repartidor_datos")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(100, 380, 101, 16))
        self.label_2.setObjectName("label_2")
        self.rb11 = QtWidgets.QRadioButton(self.centralwidget)
        self.rb11.setGeometry(QtCore.QRect(290, 380, 16, 20))
        self.rb11.setStyleSheet("background-color: rgb(170, 170, 255);")
        self.rb11.setText("")
        self.rb11.setObjectName("rb11")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 760, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_18.setText(_translate("MainWindow", "HAMBURGUESAS AMVORGUESAS"))
        self.label_14.setText(_translate("MainWindow", "Nombre"))
        self.label_15.setText(_translate("MainWindow", "Telefono"))
        self.label_16.setText(_translate("MainWindow", "Dirección"))
        self.label_17.setText(_translate("MainWindow", "Datos del cliente "))
        self.label_19.setText(_translate("MainWindow", "N. Cliente"))
        self.enviar_botton.setText(_translate("MainWindow", "ENVIAR"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Century Gothic\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:9pt;\">Papas..................................................$25</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:9pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:9pt;\">papas con queso...................................$35</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:9pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:9pt;\">Cajita Feliz............................................$38</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:9pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:9pt;\">Hamburguesa........................................$30</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:9pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:9pt;\">Hamburguesa doble...............................$60</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:9pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:9pt;\">Hamburguesa especial............................$48</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:9pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:9pt;\">Hamburguesa + papas c/Queso...............$55</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:9pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:9pt;\">Hamburguesa + papas ...........................$20</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:9pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:9pt;\">Hamburguesa + papas + Fanta de Fresa....$25</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:9pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:9pt;\">Hamburguesa + papas + Coca Cola...........$80</span></p></body></html>"))
        self.label_20.setText(_translate("MainWindow", "MENÚ"))
        self.label.setText(_translate("MainWindow", "Repartidor"))
        self.label_2.setText(_translate("MainWindow", "Pedido enviado"))
